import { EventItem, EventItemSchema } from "../../contracts/event";

export const DEMO_SHOWCASE_EVENTS: EventItem[] = [
  EventItemSchema.parse({
    id: "demo-innovation-2026",
    title: "Ngày hội Thanh niên Sáng tạo & Chuyển đổi số Liên Chiểu 2026",
    summary: "Không gian trưng bày ý tưởng số, hướng dẫn dịch vụ công trực tuyến và trải nghiệm công nghệ AI cho thanh niên.",
    description: "Sự kiện trọng điểm trong Tháng Thanh niên Liên Chiểu, quy tụ các mô hình chuyển đổi số tiêu biểu của thanh niên 10 khu dân cư và các trường đại học, cao đẳng trên địa bàn quận/phường. Hướng dẫn bà con kích hoạt VNeID mức 2, nộp hồ sơ trực tuyến và giới thiệu trợ lý AI cộng đồng.",
    category: "event_innovation",
    categoryLabel: "Sáng tạo & CĐS",
    venueName: "Trung tâm Phục vụ hành chính công phường Liên Chiểu",
    address: "68 đường Lạc Long Quân, phường Liên Chiểu, TP. Đà Nẵng",
    ward: "Phường Liên Chiểu",
    coordinates: { lat: 16.0825, lng: 108.145 },
    startAt: "2026-10-10T08:00:00+07:00",
    endAt: "2026-10-10T17:30:00+07:00",
    datePrecision: "exact",
    organizer: "Đoàn TNCS Hồ Chí Minh phường Liên Chiểu",
    targetAudience: "Đoàn viên thanh niên, sinh viên các trường ĐH/CĐ và nhân dân địa phương",
    priceText: "Miễn phí vào cổng (0đ)",
    sourceUrl: "https://danang.gov.vn",
    sourcePublisher: "Cổng thông tin điện tử phường Liên Chiểu",
    evidenceText: "Kế hoạch số 18-KH/ĐTN Đoàn phường Liên Chiểu về Tổ chức Ngày hội Thanh niên Sáng tạo vì cuộc sống 2026.",
    verificationStatus: "source_verified",
    status: "scheduled",
    isFeatured: true,
    coordinatePrecision: "venue",
    checkedAt: "2026-10-01T08:00:00+07:00",
    image: {
      src: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80",
      alt: "Không gian trải nghiệm công nghệ số thanh niên Liên Chiểu",
      kind: "event",
      sourceUrl: "https://danang.gov.vn",
      credit: "Tư liệu Hoạt động Chuyển đổi số Thanh niên Liên Chiểu",
      checkedAt: "2026-10-01T08:00:00+07:00",
    },
    sources: [
      {
        url: "https://danang.gov.vn",
        title: "Kế hoạch Ngày hội Sáng tạo Chuyển đổi số Thanh niên Liên Chiểu",
        publisher: "Đoàn Phường Liên Chiểu",
        accessStatus: "read",
        kind: "government",
        supports: ["time", "venue", "organizer", "ward", "coordinates", "price"],
        checkedAt: "2026-10-01T08:00:00+07:00",
        evidence: "Thông báo chính thức từ Đoàn TNCS Hồ Chí Minh phường Liên Chiểu.",
      },
    ],
  }),
  EventItemSchema.parse({
    id: "demo-sports-run-2026",
    title: "Giải chạy việt dã Thanh niên 'Vì một Liên Chiểu Xanh 2026'",
    summary: "Giải chạy cự ly 5km - 10km dọc cung đường biển Nguyễn Tất Thành, lan tỏa lối sống năng động và bảo vệ cảnh quan biển.",
    description: "Quy tụ hơn 500 đoàn viên, thanh niên, sinh viên và người dân tham gia chạy bộ hưởng ứng phong trào rèn luyện sức khỏe theo gương Bác Hồ vĩ đại và tuyên truyền bảo vệ môi trường vịnh Liên Chiểu - Đà Nẵng.",
    category: "event_sports",
    categoryLabel: "Thể thao",
    venueName: "Quảng trường biển Nguyễn Tất Thành",
    address: "Đường Nguyễn Tất Thành, phường Liên Chiểu, TP. Đà Nẵng",
    ward: "Phường Liên Chiểu",
    coordinates: { lat: 16.0782, lng: 108.1565 },
    startAt: "2026-10-18T06:00:00+07:00",
    endAt: "2026-10-18T10:30:00+07:00",
    datePrecision: "exact",
    organizer: "Hội Liên hiệp Thanh niên phường Liên Chiểu",
    targetAudience: "Vận động viên phong trào, thanh niên, sinh viên và người dân yêu thích thể thao",
    priceText: "Miễn phí tham gia (0đ)",
    sourceUrl: "https://danang.gov.vn",
    sourcePublisher: "Hội LHTN phường Liên Chiểu",
    evidenceText: "Điều lệ giải chạy việt dã Vì một Liên Chiểu Xanh năm 2026.",
    verificationStatus: "source_verified",
    status: "scheduled",
    isFeatured: true,
    coordinatePrecision: "venue",
    checkedAt: "2026-10-01T08:00:00+07:00",
    image: {
      src: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?auto=format&fit=crop&w=800&q=80",
      alt: "Cung đường chạy ven biển Nguyễn Tất Thành rực rỡ nắng sớm",
      kind: "event",
      sourceUrl: "https://danang.gov.vn",
      credit: "Ảnh phong trào Thể thao Thanh niên Liên Chiểu",
      checkedAt: "2026-10-01T08:00:00+07:00",
    },
    sources: [
      {
        url: "https://danang.gov.vn",
        title: "Điều lệ Giải chạy việt dã Vì một Liên Chiểu Xanh",
        publisher: "Hội LHTN Phường Liên Chiểu",
        accessStatus: "read",
        kind: "community",
        supports: ["time", "venue", "organizer", "ward", "coordinates", "price"],
        checkedAt: "2026-10-01T08:00:00+07:00",
        evidence: "Công văn phối hợp phát động phong trào thể thao thanh niên cơ sở.",
      },
    ],
  }),
  EventItemSchema.parse({
    id: "demo-cleanup-nam-o-2026",
    title: "Chiến dịch 'Chủ nhật Xanh' – Làm sạch bờ biển & Rạn Nam Ô",
    summary: "Ra quân thu gom rác thải nhựa, làm sạch bờ biển và tuyên truyền bảo tồn hệ sinh thái rạn rêu đá Nam Ô.",
    description: "Hoạt động tình nguyện định kỳ của tuổi trẻ Liên Chiểu nhằm giữ gìn mỹ quan du lịch sinh thái làng chài Nam Ô, kết hợp trao tặng thùng rác phân loại tại nguồn cho bà con ngư dân.",
    category: "event_community",
    categoryLabel: "Tình nguyện",
    venueName: "Bãi biển & Làng cổ Nam Ô",
    address: "Đường Nam Ô 1, phường Liên Chiểu, TP. Đà Nẵng",
    ward: "Phường Liên Chiểu",
    coordinates: { lat: 16.1158, lng: 108.1215 },
    startAt: "2026-10-11T07:00:00+07:00",
    endAt: "2026-10-11T11:00:00+07:00",
    datePrecision: "exact",
    organizer: "Đội Thanh niên Tình nguyện Xung kích Liên Chiểu",
    targetAudience: "Đoàn viên thanh niên, tình nguyện viên và nhân dân địa phương",
    priceText: "Tình nguyện tự do (0đ)",
    sourceUrl: "https://danang.gov.vn",
    sourcePublisher: "Đoàn Phường Liên Chiểu",
    evidenceText: "Kế hoạch Ngày Chủ nhật Xanh bảo vệ rạn Nam Ô đợt 4/2026.",
    verificationStatus: "source_verified",
    status: "scheduled",
    isFeatured: true,
    coordinatePrecision: "venue",
    checkedAt: "2026-10-01T08:00:00+07:00",
    image: {
      src: "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=800&q=80",
      alt: "Thanh niên tình nguyện chung tay làm sạch bãi biển Nam Ô",
      kind: "event",
      sourceUrl: "https://danang.gov.vn",
      credit: "Tư liệu Đội Thanh niên Tình nguyện Xung kích",
      checkedAt: "2026-10-01T08:00:00+07:00",
    },
    sources: [
      {
        url: "https://danang.gov.vn",
        title: "Chiến dịch Thanh niên Tình nguyện Môi trường Nam Ô",
        publisher: "Đoàn Phường Liên Chiểu",
        accessStatus: "read",
        kind: "community",
        supports: ["time", "venue", "organizer", "ward", "coordinates", "price"],
        checkedAt: "2026-10-01T08:00:00+07:00",
        evidence: "Lịch hoạt động tình nguyện bảo vệ bờ biển quận Liên Chiểu.",
      },
    ],
  }),
  EventItemSchema.parse({
    id: "demo-job-fair-bachkhoa-2026",
    title: "Ngày hội Hướng nghiệp & Kết nối Việc làm Sinh viên 2026",
    summary: "Kết nối hơn 30 doanh nghiệp tại KCN Hòa Khánh với sinh viên các trường ĐH, CĐ trên địa bàn Liên Chiểu.",
    description: "Cơ hội phỏng vấn trực tiếp, nộp hồ sơ ứng tuyển thực tập sinh và việc làm chính thức các ngành kỹ thuật, IT, logistics, tự động hóa; tư vấn viết CV chuẩn và kỹ năng phỏng vấn chuyên nghiệp.",
    category: "event_education",
    categoryLabel: "Học tập & Việc làm",
    venueName: "Trường Đại học Bách Khoa – ĐH Đà Nẵng",
    address: "54 Nguyễn Lương Bằng, phường Liên Chiểu, TP. Đà Nẵng",
    ward: "Phường Liên Chiểu",
    coordinates: { lat: 16.0745, lng: 108.1512 },
    startAt: "2026-10-25T08:00:00+07:00",
    endAt: "2026-10-25T16:30:00+07:00",
    datePrecision: "exact",
    organizer: "Đoàn trường ĐH Bách Khoa phối hợp Đoàn phường Liên Chiểu",
    targetAudience: "Sinh viên năm cuối, cựu sinh viên và thanh niên địa phương đang tìm kiếm việc làm",
    priceText: "Vào cửa tự do (0đ)",
    sourceUrl: "https://dut.udn.vn",
    sourcePublisher: "Đại học Bách Khoa - Đại học Đà Nẵng",
    evidenceText: "Thông báo Ngày hội Việc làm Khối ngành Kỹ thuật Công nghệ năm 2026.",
    verificationStatus: "source_verified",
    status: "scheduled",
    isFeatured: true,
    coordinatePrecision: "campus",
    checkedAt: "2026-10-01T08:00:00+07:00",
    image: {
      src: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80",
      alt: "Sinh viên giao lưu với doanh nghiệp tại ngày hội việc làm Bách Khoa",
      kind: "event",
      sourceUrl: "https://dut.udn.vn",
      credit: "Ban Truyền thông Đoàn trường ĐH Bách Khoa Đà Nẵng",
      checkedAt: "2026-10-01T08:00:00+07:00",
    },
    sources: [
      {
        url: "https://dut.udn.vn",
        title: "Thông báo Ngày hội Việc làm DUT Job Fair",
        publisher: "ĐH Bách Khoa - ĐH Đà Nẵng",
        accessStatus: "read",
        kind: "media",
        supports: ["time", "venue", "organizer", "ward", "coordinates", "price"],
        checkedAt: "2026-10-01T08:00:00+07:00",
        evidence: "Thông cáo báo chí từ Trung tâm Hỗ trợ Sinh viên và Khởi nghiệp ĐH Bách Khoa.",
      },
    ],
  }),
  EventItemSchema.parse({
    id: "demo-night-market-culture-2026",
    title: "Không gian Giao lưu Âm nhạc Đường phố & Ẩm thực Chợ đêm Hòa Khánh",
    summary: "Đêm nhạc acoustic thanh niên, biểu diễn văn nghệ đường phố và trải nghiệm ẩm thực đặc sản đêm sinh viên.",
    description: "Sân chơi âm nhạc định kỳ cuối tuần do các câu lạc bộ thanh niên thể hiện, tạo điểm hẹn văn hóa lành mạnh, sôi nổi cho giới trẻ và khách du lịch khám phá đời sống ẩm thực Liên Chiểu về đêm.",
    category: "event_culture",
    categoryLabel: "Văn hóa & Phố đêm",
    venueName: "Phố ẩm thực Chợ đêm Hòa Khánh",
    address: "Đường Âu Cơ, phường Liên Chiểu, TP. Đà Nẵng",
    ward: "Phường Liên Chiểu",
    coordinates: { lat: 16.0682, lng: 108.1438 },
    startAt: "2026-10-17T19:00:00+07:00",
    endAt: "2026-10-17T22:30:00+07:00",
    datePrecision: "exact",
    organizer: "CLB Nghệ thuật Thanh niên Liên Chiểu",
    targetAudience: "Thanh thiếu nhi, sinh viên, người dân và du khách",
    priceText: "Vào cửa tự do (0đ)",
    sourceUrl: "https://danang.gov.vn",
    sourcePublisher: "CLB Nghệ thuật Thanh niên Liên Chiểu",
    evidenceText: "Lịch biểu diễn định kỳ Phố âm nhạc và ẩm thực đêm sinh viên Hòa Khánh.",
    verificationStatus: "source_verified",
    status: "scheduled",
    isFeatured: true,
    coordinatePrecision: "venue",
    checkedAt: "2026-10-01T08:00:00+07:00",
    image: {
      src: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
      alt: "Phố ẩm thực đêm Hòa Khánh rực rỡ ánh đèn và không gian âm nhạc",
      kind: "venue",
      sourceUrl: "https://danang.gov.vn",
      credit: "Tư liệu Không gian Văn hóa Thanh niên Liên Chiểu",
      checkedAt: "2026-10-01T08:00:00+07:00",
    },
    sources: [
      {
        url: "https://danang.gov.vn",
        title: "Chương trình Nghệ thuật Đường phố Thanh niên Liên Chiểu",
        publisher: "CLB Nghệ thuật Thanh niên Liên Chiểu",
        accessStatus: "read",
        kind: "community",
        supports: ["time", "venue", "organizer", "ward", "coordinates", "price"],
        checkedAt: "2026-10-01T08:00:00+07:00",
        evidence: "Kế hoạch tổ chức chuỗi sự kiện âm nhạc cộng đồng cuối tuần.",
      },
    ],
  }),
];
