import { ActionType, Domain, Intent, Profile, Stress } from "./types";

export const CATALOG: Record<Domain, [string, string][]> = {
  cu_tru: [
    ["nhận diện việc cần hỏi khi mới thuê trọ", "không nhầm nhu cầu với thủ tục khác"],
    ["lập phiếu chuẩn bị trước khi đăng ký tạm trú", "biết điều đã rõ và điều cần xác minh"],
    ["chuẩn bị câu hỏi cần trao đổi với chủ nhà", "không tự kết luận giấy tờ thay chủ nhà"],
    ["mở đúng kênh chính thức về đăng ký tạm trú", "tiếp tục thao tác trên kênh có thẩm quyền"],
    ["tìm bước tiếp theo khi không đăng nhập được kênh cư trú", "nhận hỗ trợ mà không giao mật khẩu hay OTP"],
    ["hiểu cần hỏi gì khi hồ sơ tạm trú được yêu cầu bổ sung", "làm rõ yêu cầu mà không tự suy đoán quyết định"],
    ["tiếp tục phiếu chuẩn bị tạm trú đang làm dở", "không phải kể lại toàn bộ nhu cầu"],
    ["mang phiếu vướng mắc tạm trú đến người hỗ trợ", "người hỗ trợ hiểu việc còn vướng"],
    ["chuyển từ nhu cầu tạm trú sang thường trú", "được chuyển sang nguồn đúng phạm vi"],
    ["hỏi trường hợp cư trú có tranh chấp hoặc yếu tố quốc tịch", "được người có thẩm quyền xem xét trường hợp riêng"],
  ],
  kinh_doanh: [
    ["tìm hiểu trước khi mở quán ăn sáng", "biết các điều kiện cần xác minh trước khi đầu tư"],
    ["chuẩn bị mở quán cà phê", "không bỏ sót đầu mối cần hỏi"],
    ["bán đồ ăn làm tại nhà", "xác định trường hợp áp dụng qua nguồn chính thức"],
    ["mở tiệm sửa xe", "kiểm tra yêu cầu phù hợp loại hình"],
    ["bán hàng qua mạng", "phân biệt hướng dẫn chung với nghĩa vụ cụ thể"],
    ["thay đổi địa điểm hộ kinh doanh", "biết nơi xác minh thủ tục thay đổi"],
    ["tạm ngừng hoạt động kinh doanh", "tìm đúng hướng dẫn hiện hành"],
    ["hiểu việc sử dụng hóa đơn cho cơ sở nhỏ", "không áp dụng thông tin thuế lỗi thời"],
    ["hỏi điều kiện đặt biển hiệu cửa hàng", "không suy đoán quyền sử dụng không gian công cộng"],
    ["chuẩn bị câu hỏi về an toàn cơ sở kinh doanh", "nhận hướng dẫn chuyên môn theo từng trường hợp"],
  ],
  hoc_tap: [
    ["tìm trường mầm non sau khi chuyển chỗ ở", "kiểm tra thông tin tuyển sinh phù hợp"],
    ["tìm hướng dẫn vào lớp một", "biết nguồn thông báo theo năm học"],
    ["xin chuyển trường giữa năm", "xác minh đầu mối và điều kiện tiếp nhận"],
    ["hỏi trường hợp thiếu giấy tờ nhập học", "được trường giải đáp trường hợp riêng"],
    ["tìm thông tin hỗ trợ học phí", "không bị hứa chắc quyền lợi"],
    ["tìm lớp học nghề", "so sánh cơ hội từ nguồn kiểm chứng"],
    ["tìm lớp kỹ năng số miễn phí", "biết lịch và đơn vị tổ chức đã xác nhận"],
    ["tìm học bổng cho học sinh khó khăn", "biết điều kiện và hạn nộp thực tế"],
    ["tìm hỗ trợ cho người học khuyết tật", "tiếp cận đầu mối phù hợp"],
    ["hỏi chỗ học khi đã hết đợt tuyển sinh", "nhận phương án từ đơn vị có thẩm quyền"],
  ],
  y_te: [
    ["tìm lịch tiêm chủng của trạm y tế", "xác nhận lịch còn hiệu lực"],
    ["hỏi nơi liên hệ khi mất sổ tiêm", "tránh tự đoán lịch tiêm cá nhân"],
    ["tìm cơ sở khám gần nơi ở", "kiểm tra thông tin cơ sở chính thức"],
    ["tìm thông tin tham gia bảo hiểm y tế", "biết nguồn hướng dẫn phù hợp"],
    ["hỏi việc chuyển nơi khám ban đầu", "xác minh quy định hiện hành"],
    ["tìm hỗ trợ chăm sóc người cao tuổi", "liên hệ dịch vụ được xác minh"],
    ["tìm đầu mối tư vấn sức khỏe tinh thần", "tiếp cận hỗ trợ chuyên môn"],
    ["tìm thông tin chương trình khám cộng đồng", "không đến nhầm lịch cũ"],
    ["tìm kênh phản ánh cơ sở y tế", "gửi phản ánh đúng nơi"],
    ["hỏi nơi trợ giúp khi xuất hiện triệu chứng bất thường", "không nhận chẩn đoán từ công cụ dân sinh"],
  ],
  an_sinh: [
    ["tìm đầu mối hỗ trợ khó khăn đột xuất", "biết nơi trình bày hoàn cảnh"],
    ["tìm thông tin trợ giúp người khuyết tật", "xác minh điều kiện qua cơ quan phụ trách"],
    ["tìm hỗ trợ trẻ em khó khăn", "bảo vệ dữ liệu của trẻ"],
    ["hỏi trợ giúp người cao tuổi", "biết điều kiện cần xác minh"],
    ["tìm hỗ trợ nhà ở cho người lao động", "không nhầm quảng cáo với chính sách"],
    ["hỏi nguồn thực phẩm hỗ trợ cộng đồng", "xác nhận chương trình còn hoạt động"],
    ["tìm hỗ trợ cho gia đình gặp thiên tai", "biết đầu mối có thẩm quyền"],
    ["tìm kênh bảo vệ người bị bạo lực", "chuyển tới hỗ trợ chuyên trách"],
    ["tìm chương trình hỗ trợ dịp lễ", "kiểm tra phạm vi và thời gian"],
    ["hỏi việc bổ sung hồ sơ trợ cấp", "không suy diễn khả năng được duyệt"],
  ],
  viec_lam: [
    ["tìm việc làm theo ca", "kiểm tra đơn vị tuyển dụng"],
    ["tìm việc bán thời gian cho sinh viên", "tránh phải nộp phí không rõ ràng"],
    ["tìm vị trí thực tập", "biết cách liên hệ đơn vị thật"],
    ["tìm lớp đào tạo chuyển nghề", "xác nhận lịch và điều kiện tham gia"],
    ["tìm nguồn hỗ trợ viết hồ sơ xin việc", "không gửi dữ liệu cá nhân công khai"],
    ["tìm đầu mối khi bị nợ lương", "được chuyển tới tư vấn chuyên môn"],
    ["hỏi thông tin trợ cấp thất nghiệp", "tra đúng nguồn hiện hành"],
    ["tìm cơ hội cho người lao động khuyết tật", "xác nhận điều kiện công việc"],
    ["kiểm tra thông tin tuyển dụng đáng ngờ", "không bị công cụ khẳng định an toàn khi chưa xác minh"],
    ["tìm thông tin ngày hội việc làm", "biết sự kiện còn hiệu lực"],
  ],
  moi_truong: [
    ["tìm lịch thu gom rác", "kiểm tra tuyến và lịch hiện hành"],
    ["hỏi cách phân loại rác tại nơi ở", "theo đúng hướng dẫn thu gom địa phương"],
    ["tìm nơi tiếp nhận đồ cồng kềnh", "không tự chọn điểm đổ bỏ"],
    ["tìm đơn vị tiếp nhận phế thải xây dựng", "xác minh nơi được phép tiếp nhận"],
    ["phản ánh điểm đổ rác tự phát", "dùng kênh tiếp nhận chính thức"],
    ["phản ánh tiếng ồn khu dân cư", "trình bày thông tin cần thiết"],
    ["phản ánh đèn đường hỏng", "gửi đúng vị trí và nơi tiếp nhận"],
    ["tìm nơi tiếp nhận pin cũ", "xác nhận điểm thu gom còn hoạt động"],
    ["đăng ký hoạt động làm sạch khu phố", "xác nhận đơn vị tổ chức"],
    ["phản ánh thoát nước bị tắc", "phân biệt phản ánh thường với tình huống nguy hiểm"],
  ],
  dia_diem: [
    ["tìm điểm tiếp nhận hành chính phục vụ nơi mới đến", "kiểm tra đúng địa bàn và đúng chức năng thay vì chỉ gần nhất"],
    ["tìm đầu mối Công an phụ trách cư trú", "không tới nhầm trụ sở cấp quận cũ"],
    ["tìm trạm y tế được giới thiệu cho khu vực", "kiểm tra địa chỉ và cách liên hệ"],
    ["tìm điểm hỗ trợ số cho người mới đến", "biết điểm đã có người phụ trách xác nhận"],
    ["tìm địa điểm thiết yếu khi không chia sẻ GPS", "chọn khu vực thủ công mà vẫn xem được danh bạ"],
    ["mở chỉ đường tới một địa điểm đã chọn", "giao chỉ đường cho ứng dụng bản đồ thay vì bịa khoảng cách"],
    ["kiểm tra địa điểm trước khi đi ngoài giờ", "phân biệt giờ đã xác minh và giờ chưa biết"],
    ["lưu thẻ địa điểm và nguồn để hỏi lại", "mang theo thông tin mà không cần tài khoản"],
    ["tìm bến xe buýt và chuyến đang chạy gần đây", "không nhận lịch trình thời gian thực khi chưa có dữ liệu"],
    ["tìm trường gần nhà có thể tiếp nhận học sinh", "không đánh đồng gần nhà với đúng tuyến hoặc còn chỗ"],
  ],
  van_hoa: [
    ["khám phá một địa điểm địa phương có nguồn giới thiệu", "biết câu chuyện và hành động tiếp theo"],
    ["đọc câu chuyện văn hóa của nơi vừa đến", "phân biệt tư liệu xác minh với nội dung sáng tác"],
    ["lưu một điểm muốn tham quan", "tự chọn đi tiếp mà không bị gợi ý lịch trình thiếu căn cứ"],
    ["tìm hiểu di tích trong phường", "phân biệt địa giới hiện hành"],
    ["tìm sản phẩm OCOP địa phương", "kiểm tra chứng nhận còn phù hợp"],
    ["tìm thông tin tham quan Nam Ô", "nhận chỉ dẫn đúng địa bàn thay vì gán nhầm phường"],
    ["tìm sự kiện cuối tuần", "kiểm tra thông báo còn hiệu lực"],
    ["tìm nơi mượn sách", "xác nhận giờ hoạt động"],
    ["đăng ký tham gia tình nguyện", "biết đơn vị tiếp nhận đã xác nhận"],
    ["tìm thông tin sản phẩm thanh niên", "phân biệt giới thiệu với bảo chứng chất lượng"],
  ],
  du_lich_su_kien: [
    ["chọn hành trình tham quan trong hai giờ", "tính cả thời gian đi lại và điều kiện mở cửa"],
    ["tìm sự kiện thực sự diễn ra hôm nay", "không nhận lễ hội năm 2024 như sự kiện hiện tại"],
    ["tìm món ăn địa phương phù hợp ngân sách", "phân biệt thông tin giới thiệu với giá đã kiểm chứng"],
    ["đi tham quan cùng người khó đi lại", "xác minh điều kiện tiếp cận thay vì tự suy đoán"],
    ["đi khám phá khi trời mưa", "không được công cụ bảo đảm an toàn ngoài khả năng"],
    ["tìm trải nghiệm phù hợp cho trẻ nhỏ", "xác minh dịch vụ và người tổ chức"],
    ["chọn điểm tham quan ngoài phường", "thấy rõ nhãn ngoài địa bàn và nguồn tương ứng"],
    ["kiểm tra một địa điểm có còn mở cửa", "không nhầm nội dung cũ với trạng thái thời gian thực"],
    ["tìm nơi mua đặc sản có nguồn gốc", "không nhận đánh giá sao hoặc chứng nhận được bịa ra"],
    ["hỏi hỗ trợ khi bị lạc trong chuyến tham quan", "được chuyển tới trợ giúp phù hợp"],
  ],
};

export const PROFILES: Profile[] = [
  { id: "P01", name: "người có thể tự thao tác trên điện thoại cá nhân", mode: "self", adaptation: "hiển thị ngắn, rõ từng bước" },
  { id: "P02", name: "người ít quen thao tác số", mode: "low_literacy", adaptation: "câu ngắn, lựa chọn rõ, luôn có nút nhờ hỗ trợ" },
  { id: "P03", name: "người không có điện thoại thông minh, xem qua người hỗ trợ", mode: "no_device", adaptation: "phiếu in hoặc xem cùng người hỗ trợ; không ép tạo tài khoản" },
  { id: "P04", name: "người làm việc theo ca, chỉ rảnh ngoài giờ", mode: "shift", adaptation: "lưu phiếu tự nguyện; không hứa có người trực 24/7" },
  { id: "P05", name: "người dùng máy dùng chung tại điểm hỗ trợ", mode: "shared", adaptation: "không lưu bền mặc định; kết thúc phiên phải xóa dữ liệu" },
  { id: "P06", name: "người khó đi lại", mode: "mobility", adaptation: "ưu tiên kênh tiếp cận từ xa đã xác minh, không hứa xử lý tại nhà" },
  { id: "P07", name: "người đang hỗ trợ người thân có sự đồng ý", mode: "proxy_yes", adaptation: "hỗ trợ thao tác không đồng nghĩa đại diện pháp lý" },
  { id: "P08", name: "người muốn làm giúp nhưng chưa hỏi ý kiến người liên quan", mode: "proxy_no", adaptation: "chỉ hướng dẫn chung; không tạo hoặc chia sẻ phiếu cá nhân" },
  { id: "P09", name: "người đọc tiếng Việt chưa thành thạo", mode: "language", adaptation: "bản dịch chỉ trợ đọc; trường hợp cần hiểu chính xác phải có hỗ trợ" },
  { id: "P10", name: "người quay lại sau lần trước còn vướng", mode: "returning", adaptation: "khôi phục thông tin tự chọn và hỏi việc còn vướng, không giả định hồ sơ đã nộp" },
];

export const STRESSES: Stress[] = [
  { id: "S01", name: "thông tin tối thiểu đã rõ, nguồn và đầu mối trong mô hình đã được duyệt", flag: "clean", hazard: "không biến phiếu chuẩn bị thành kết luận đủ điều kiện" },
  { id: "S02", name: "chỉ biết tên quận cũ, chưa xác định phường hiện tại", flag: "unknown_area", hazard: "không đoán địa giới từ tên đường hoặc tên quận cũ" },
  { id: "S03", name: "xác nhận việc cần giải quyết ở ngoài phường Liên Chiểu", flag: "outside", hazard: "không áp hướng dẫn địa phương sang nơi khác" },
  { id: "S04", name: "nguồn hướng dẫn đã quá ngày rà soát quy định trong bộ dữ liệu", flag: "stale", hazard: "không trình bày dữ liệu cũ như đang còn hiệu lực" },
  { id: "S05", name: "hai nguồn chính thức đưa thông tin khác nhau", flag: "conflict", hazard: "không tự chọn nguồn thuận tiện hoặc ghép hai phiên bản" },
  { id: "S06", name: "người dùng chưa biết một điều kiện quyết định nhánh", flag: "missing_fact", hazard: "cho phép không biết; không tự điền điều kiện" },
  { id: "S07", name: "người dùng định dán ảnh căn cước hoặc mã đăng nhập vào ô hỏi", flag: "sensitive", hazard: "chặn đầu vào nhạy cảm trước khi gửi ra dịch vụ ngoài" },
  { id: "S08", name: "mất mạng sau khi đã mở được phiếu, không thể kiểm tra phiên bản mới", flag: "offline", hazard: "chỉ xem lại phiếu có mốc thời gian; không khẳng định vừa xác minh" },
  { id: "S09", name: "dịch vụ AI hết hạn mức hoặc không phản hồi", flag: "ai_down", hazard: "luồng lựa chọn và phiếu đã duyệt vẫn phải dùng được" },
  { id: "S10", name: "đang có nguy cơ an toàn tức thời tại nơi ở hoặc nơi người dùng hiện diện", flag: "urgent", hazard: "ưu tiên tìm trợ giúp khẩn phù hợp, không tiếp tục hỏi thủ tục" },
];

export const ACTION_TEXT: Record<ActionType, string> = {
  PREPARE: "Tạo phiếu chuẩn bị theo nhánh đã duyệt; thể hiện điều đã biết, điều cần hỏi, nguồn và bước tiếp theo.",
  ASK_AREA: "Hỏi lại phường hiện tại hoặc hỗ trợ xác minh địa bàn; chưa xuất checklist địa phương.",
  OUTSIDE: "Thông báo ngoài địa bàn; mở danh mục chính thức để người dùng chọn nơi phù hợp.",
  REVIEW_SOURCE: "Tạm ngừng chi tiết bị ảnh hưởng; hiển thị nhu cầu cần xác minh và đầu mối đã xác nhận nếu có.",
  ASK_FACT: "Hỏi một điều kiện còn thiếu bằng lựa chọn có phương án không biết; nếu vẫn thiếu, lập phiếu câu hỏi.",
  REMOVE_SENSITIVE: "Không nhận ảnh giấy tờ, mật khẩu, OTP; bỏ nội dung nhạy cảm và tiếp tục bằng thông tin phân loại.",
  OFFLINE_VIEW: "Xem lại phiếu và ngày rà soát đã lưu tự nguyện; chờ có mạng để xác minh tiếp, không gửi gì.",
  URGENT_HELP: "Dừng hành trình thủ tục; ưu tiên liên hệ trợ giúp khẩn đã xác minh hoặc người hỗ trợ tại chỗ.",
  GENERAL_ONLY: "Chỉ hiển thị hướng dẫn chung; không cá nhân hóa hoặc chia sẻ thông tin người khác khi chưa có đồng ý.",
  LANGUAGE_HELP: "Dùng hướng dẫn đơn giản và đề nghị trợ đọc; không kết luận pháp lý từ bản dịch tự động.",
  OFFICIAL_REDIRECT: "Nêu rõ chưa hỗ trợ nhu cầu này; dẫn danh mục chính thức, không bịa câu trả lời để giữ người dùng.",
};

export const INTENTS: Intent[] = Object.entries(CATALOG).flatMap(([domain, goals]) =>
  goals.map(([goal, benefit], i) => ({
    id: `${domain}-${String(i + 1).padStart(2, "0")}`,
    domain: domain as Domain,
    goal,
    benefit,
  }))
);

export const ALL_INTENT_IDS = new Set(INTENTS.map((i) => i.id));
export const RESIDENCE_IDS = new Set(Array.from({ length: 8 }, (_, i) => `cu_tru-${String(i + 1).padStart(2, "0")}`));
export const PLACE_IDS = new Set(Array.from({ length: 8 }, (_, i) => `dia_diem-${String(i + 1).padStart(2, "0")}`));
export const DISCOVERY_IDS = new Set(Array.from({ length: 3 }, (_, i) => `van_hoa-${String(i + 1).padStart(2, "0")}`));
export const MVP_IDS = new Set([...RESIDENCE_IDS, ...PLACE_IDS, ...DISCOVERY_IDS]);
